version: 2
jobs:
  build:
    machine: true
    steps:
      - run: echo 'export PATH=./Nim/bin:$PATH' >> $BASH_ENV
      - checkout
      # Reuse cached Nim compiler
      - restore_cache:
          key: compiler-0000
      - run:
          command: |
            if [ -d Nim ]; then
              cd Nim
              git fetch
              if [ "$(git rev-parse HEAD)" == "$(git rev-parse @{u})" ]; then
                echo "Nim is up to date"
                build_nim=false
              else
                echo "pulling new Nim commits"
                build_nim=true
                git pull
              fi
            else
              echo "cloning Nim for the first time"
              build_nim=true
              git clone --depth 1 https://github.com/nim-lang/Nim.git
              cd Nim
              git clone --depth 1 git://github.com/nim-lang/csources.git csources
              cd csources
              sh build.sh
              cd ..
            fi
            if [ "$build_nim" = true ]; then
              ./bin/nim c koch
              ./koch boot -d:release
              ./koch tools
            fi
      - save_cache:
          key: compiler-0000
          paths:
            - Nim
      - run: nimble build -y
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
